### ISSUE TITLE
Error installing libax25-devel due to header conflicts with glibc-headers

### ISSUE THREAD

**Issue by hobbes1069** [ve7fet/linuxax25#1]
I'm considering moving the Fedora packages over to your fork and was doing to local builds for testing when I ran into this issue.

```
Error: Transaction check error:
  file /usr/include/netax25/ax25.h from install of libax25-devel-1.0.5-1.fc21.x86_64 conflicts with file from package glibc-headers-2.20-8.fc21.x86_64
  file /usr/include/netrom/netrom.h from install of libax25-devel-1.0.5-1.fc21.x86_64 conflicts with file from package glibc-headers-2.20-8.fc21.x86_64
  file /usr/include/netrose/rose.h from install of libax25-devel-1.0.5-1.fc21.x86_64 conflicts with file from package glibc-headers-2.20-8.fc21.x86_64
```

**Comment by hobbes1069** [comment]
Doing some googling this seems to be a pretty old problem to not be solved.

Could we not put the headers into a named subdirectory? i.e. /usr/include/ax25/...? I'm not sure how to do it in autotools but in cmake you can prepend (as opposed to append) include search directories to make sure the libax25 ones are found first.

**Comment by f6bvp** [comment]
Hi,
I suggest you uninstall Fedora ax25 package to avoid conflicts. This will also remove old unmatched libraries.
I had the same kind of conflicts when installing an APRS igate package recently that included (why ?) some ax25 libraries.

73 de Bernard f6bvp

**Comment by k4gbb** [comment]
When you compile an app with the option to create a Debian pkg the program
includes all of the dependent files and libs. I have forgotten the exact
cmd. The process was meant to generate a .deb pkg for private use. It is
not intendended to be used for public releases.

I used the cmd several times until I realized it was including many of my
personel system files.

<<Charley>>

**Comment by hobbes1069** [comment]
Ok, I'll attempt to answer both of you. 

There's no Fedora "ax25" package to be removed, it's conflict with glibc-headers, not something you can just yank out.

One thing I'm trying to determine is why glibc is distributing these headers at all. Are they needed to build the kernel module?

Charley, I'm not sure what you mean. I'm packaging for Fedora, not Debian (or derivitives) I'm using the standard "make install" method through rpmbuild which creates the RPM package.

Again, I'm not sure how what you're saying would fix a conflict with a required package (glibc).

**Comment by k4gbb** [comment]
I was trying to explain WHY Bernard's Igate package contained the extra lib
files.

<<Charlie>>

**Comment by dranch** [comment]
The conflicting header files come from Glibc itself so there isn't much you can do here.  Though a pain, what I do is when a Glibc update comes along and complains about the conflict, I run this script:

#Written to support both rpm and deb based systems
http://www.trinityos.com/HAM/CentosDigitalModes/usr/local/sbin/update-glibc-ax25-workaround.sh

--David

**Comment by ve7fet** [comment]
Cleanup.
