### ISSUE TITLE
 need for development tools to be added in README

### ISSUE THREAD

**Issue by f6bvp** [ve7fet/linuxax25#14]
While installing AX25 on a brand new Raspberry OS I started to install AX25 libraries.
However a few utilities and libraries necessary for compilation and installation where missing.
Although Raspbian OS build-essential packages are already installed in raspbian OS it is not bad to check.

The following should be added more explicitely in README file.
****
Mandatory tools and libraries necessary for AX25 libraries, apps and tools installation : 
sudo apt install build-essential libtool libncursesw5-dev libncurses5-dev autoconf make
***
73 de Bernard, f6bvp

**Comment by dranch** [comment]
I have this documented here ( https://www.trinityos.com/HAM/CentosDigitalModes/RPi/rpi4-setup.html#18.install-ax25 ) including recommended approaches to package them into deb files.

**Comment by f6bvp** [comment]
Hi David,

Thank you for providing information on your document.

What I wanted was to set up a minimal AX25 test bed on a brand new 
Raspbian Os system.

I deliberately started from Lee's ve7fet repository and not from my own 
nodes configurations or howto pages in order to find what was the 
minimal previous libraries and tools to install AX25 libraries, 
ax25tools and ax25apps.

Then I found it could be interesting to share the result by adding this 
information into Lee ve7fed README file.

As Dave Van der Locht explained in the following Linux-ham thread

*Re: Status of the stuck sockets bugs. 
<https://marc.info/?t=162498801000003&r=1&w=2>*

https://marc.info/?l=linux-hams&m=162710906716998&w=2

can be easily reproduced.

I would like to know if it is possible to set up a very minimal AX25 
over IP configuration allowing connexion between two consoles on the 
same computer ?

Then perform the same test coneexion using NetRom or Rose protocols on 
the same local computer ?

Is there any litterature on how this could be done.

This would help others willing to work on AX25 and ROSE bugs without the 
need of a complex installation-configuration like ROSE/FPAC.

-- 
73 de Bernard, f6bvp

http://radiotelescope-lavillette.fr/
http://f6bvp.org

Le 23/09/2021 à 19:34, David Ranch a écrit :

**Comment by ve7fet** [comment]
Added some comments to the README on packages to install when building/installing from source.

See commit:

[ecbd544](https://github.com/ve7fet/linuxax25/commit/ecbd544bbc8f2ddce1265c6a8116ec4da4825128)
