### ISSUE TITLE
"Releases" link not found  

### ISSUE THREAD

**Issue by f6bvp** [ve7fet/linuxax25#15]
In README 

***Building from Source***
See the "Releases" link on this page to download the current source tarballs.

should be replaced by : 

***Building from Source***
See README files in libax25, ax25tools, ax25apps directories

**Comment by ve7fet** [comment]
Updated the README.

See commit:

[300fd25](https://github.com/ve7fet/linuxax25/commit/300fd25d8b3151cd51951193ac5d4b05904a8c44)

**Comment by f6bvp** [comment]
Hi Lee,

I would like to thank you for all excellent commits you have just 
published for libtools and other applications.

They solved compilation issues on my updated Ubuntu 23-04.

Only a number of warnings are remaining about return value of ‘write’.

warning: ignoring return value of ‘write’ declared with attribute 
‘warn_unused_result’ [-Wunused-result]

They should be easily removed by adding integer variables to receive 
write() returned values.

After that I wonder if something could not be done such as new releases 
for libax25, ax25tools and ax25apps in order to advertise the fact that 
packages can be used as is.

73 de Bernard, f6bvp / ai7bg


Le 31/07/2023 à 21:41, Lee Woldanski a écrit :

**Comment by ve7fet** [comment]
Yes, I am aware of the write warnings, I was looking at a way to handle them.

However, the first thing I am going to do while I sit here on vacation, is to try and update all the recent changes from 2018+ into the code base first. Then, I will try and fix some of those remaining warnings.

I started pushing some changes to libax25 this morning, and will continue the process as time allows.

Lee
