### ISSUE TITLE
Compile fail for ax25tools at axgetput.c under latest Xubuntu (stretch)

### ISSUE THREAD

**Issue by kq6up** [ve7fet/linuxax25#16]
root@fig:/home/chris/ve7fet/ax25tools# make
make  all-recursive
make[1]: Entering directory '/home/chris/ve7fet/ax25tools'
Making all in ax25
make[2]: Entering directory '/home/chris/ve7fet/ax25tools/ax25'
Making all in axgetput
make[3]: Entering directory '/home/chris/ve7fet/ax25tools/ax25/axgetput'
gcc -DHAVE_CONFIG_H -I. -I../..  -D_GNU_SOURCE   -g -O2 -MT axgetput.o -MD -MP -MF .deps/axgetput.Tpo -c -o axgetput.o axgetput.c
In file included from axgetput.c:18:
../../config.h:308:16: error: two or more data types in declaration specifiers
  308 | #define mode_t int
      |                ^~~
../../config.h:311:15: error: two or more data types in declaration specifiers
  311 | #define pid_t int
      |               ^~~
axgetput.c: In function ‘eol_convention’:
axgetput.c:113:17: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  113 |                 write(fderr, BIN_ON, strlen(BIN_ON));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
axgetput.c:116:17: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  116 |                 write(fderr, BIN_OFF, strlen(BIN_OFF));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:380: axgetput.o] Error 1
make[3]: Leaving directory '/home/chris/ve7fet/ax25tools/ax25/axgetput'
make[2]: *** [Makefile:595: all-recursive] Error 1
make[2]: Leaving directory '/home/chris/ve7fet/ax25tools/ax25'
make[1]: *** [Makefile:392: all-recursive] Error 1
make[1]: Leaving directory '/home/chris/ve7fet/ax25tools'
make: *** [Makefile:331: all] Error 2

**Comment by dranch** [comment]
Here is a working patch I came up with back on 9/22/22:

ax25tools-gcc11-fixes.patch
-------------------------------------------------------------------------------------------------------
--- ax25/axgetput/axgetput.c.orig    2022-09-21 09:52:27.435144017 -0700
+++ ax25/axgetput/axgetput.c    2022-09-21 10:02:10.099454962 -0700
@@ -14,6 +14,8 @@
  *
  */

+#include <sys/types.h>
+
 #ifdef HAVE_CONFIG_H
 #include <config.h>
 #endif


--- ax25/beacon.c.orig    2022-09-21 10:06:09.105941772 -0700
+++ ax25/beacon.c    2022-09-21 10:06:33.681786202 -0700
@@ -1,3 +1,4 @@
+#include <sys/types.h>
 #include <config.h>
 #include <unistd.h>
 #include <stdio.h>


--- rose/rsuplnk.c.orig    2022-09-21 10:21:51.504492235 -0700
+++ rose/rsuplnk.c    2022-09-21 10:23:33.903936174 -0700
@@ -1,3 +1,4 @@
+#include <sys/types.h>
 #include <stdio.h>
 #include <string.h>
 #include <unistd.h>


--- ./rose/rsdwnlnk.c.orig    2022-09-21 10:36:20.171506951 -0700
+++ ./rose/rsdwnlnk.c    2022-09-21 10:37:31.995078639 -0700
@@ -1,3 +1,4 @@
+#include <sys/types.h>
 #include <stdio.h>
 #include <string.h>
 #include <unistd.h>


--- ./tcpip/rip98d.c.orig    2022-09-21 10:40:31.466003550 -0700
+++ ./tcpip/rip98d.c    2022-09-21 10:40:51.537882952 -0700
@@ -1,4 +1,4 @@
-
+#include <sys/types.h>
 #ifdef HAVE_CONFIG_H
 #include <config.h>
 #endif


--- configure.ac.orig    2022-09-21 10:10:52.756146179 -0700
+++ configure.ac    2022-09-21 10:11:20.035973476 -0700
@@ -80,7 +80,6 @@
 dnl Checks for library functions.
 AC_FUNC_CHOWN
 AC_FUNC_FORK
-AC_FUNC_MALLOC
 AC_FUNC_MEMCMP
 AC_FUNC_SELECT_ARGTYPES
 AC_TYPE_SIGNAL
-------------------------------------------------------------------------------------------------------

mv ax25tools-gcc11-fixes.patch ax25tools
cd ax25tools
patch -p0 < ax25tools-gcc11-fixes.patch 
make -j2

**Comment by f6bvp** [comment]
Hi,

There is no <sys/types.h> on my Ubuntu distro.
Consequently, after applying your patches there are still compile errors with

gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.


Such as :

In file included from rip98d.c:3:
../config.h:301:15: error: two or more data types in declaration specifiers
  301 | #define pid_t int
      |               ^~~

and the same

In file included from rsdwnlnk.c:8:
../config.h:301:16: error: two or more data types in declaration specifiers
  301 | #define mode_t int
      |                ^~~

73 de Bernard, f6bvp

**Comment by dranch** [comment]
Consider trying the following to see if these bring in some missing dependencies:

sudo apt install build-essential
sudo apt install zlib1g-dev
sudo apt install libncursesw5-dev

**Comment by f6bvp** [comment]
All these are already installed with the most recent versions.

**Comment by f6bvp** [comment]
Commenting the following in config.h removed these compile errors.
10 /* Define as a signed integer type capable of holding a process identifier. */
311 /*#define pid_t int*/
312 
313 /* Define to `unsigned int' if <sys/types.h> does not define. */
314 /* #undef size_t */
315 
However this is not the definite solution.

**Comment by f6bvp** [comment]
And this one must also be commented in order to achieve complete install of ax25tools

 /* Define to rpl_malloc if the replacement function should be used. */
305 //#define malloc rpl_malloc                                                                                         
306

**Comment by f6bvp** [comment]
Part of 
root@bernard-f6bvp:/usr/local/src/ax25/linuxax25-master/ax25tools-patchés# ll /usr/local/sbin/
total 8368
drwxr-xr-x  2 root root    4096 juil. 29 17:38 ./
drwxr-xr-x 11 root root    4096 août   4  2022 ../
-rwxr-xr-x  1 root root   34240 juil. 29 17:38 ax25_call*
-rwxr-xr-x  1 root root   83168 juil. 29 17:38 ax25d*
-rwxr-xr-x  1 root root   24272 juil. 29 17:38 axctl*
-rwxr-xr-x  1 root root   40672 juil. 29 17:38 axparms*
-rwxr-xr-x  1 root root  136072 juil. 29 17:38 axspawn*
-rwxr-xr-x  1 root root   26752 juil. 29 17:38 axwrapper*
-rwxr-xr-x  1 root root   28720 juil. 29 17:38 beacon*
-rwxr-xr-x  1 root root   26960 juil. 29 17:38 bpqparms*
...

**Comment by f6bvp** [comment]
-rwxr-xr-x  1 root root   41440 juil. 29 17:38 kissattach*
-rwxr-xr-x  1 root root   41992 juil. 29 17:38 kissnetd*
-rwxr-xr-x  1 root root   28864 juil. 29 17:38 kissparms*
-rwxr-xr-x  1 root root   42624 juil. 29 17:38 m6pack*
-rwxr-xr-x  1 root root   23680 juil. 29 17:38 mcs2h*
-rwxr-xr-x  1 root root   40248 juil. 29 17:38 mheardd*
-rwxr-xr-x  1 root root   48544 juil. 29 17:38 mkiss*
-rwxr-xr-x  1 root root   53728 juil. 29 17:38 net2kiss*
-rwxr-xr-x  1 root root   34408 juil. 29 17:38 netrom_call*
-rwxr-xr-x  1 root root   75648 juil. 29 17:38 netromd*
-rwxr-xr-x  1 root root   28616 juil. 29 17:38 nodesave*
-rwxr-xr-x  1 root root   30632 juil. 29 17:38 nrattach*
-rwxr-xr-x  1 root root   29928 juil. 29 17:38 nrparms*
-rwxr-xr-x  1 root root   33856 juil. 29 17:38 nrsdrv*
-rwxr-xr-x  1 root root   52704 juil. 29 17:38 rip98d*
-rwxr-xr-x  1 root root   34744 juil. 29 17:38 rose_call*
-rwxr-xr-x  1 root root   29504 juil. 29 17:38 rsattach*
-rwxr-xr-x  1 root root   28976 juil. 29 17:38 rsdwnlnk*
-rwxr-xr-x  1 root root   28176 juil. 29 17:38 rsmemsiz*
-rwxr-xr-x  1 root root   31304 juil. 29 17:38 rsparms*
-rwxr-xr-x  1 root root   31224 juil. 29 17:38 rsuplnk*
-rwxr-xr-x  1 root root    2319 juil. 29 17:38 rsusers.sh*
-rwxr-xr-x  1 root root   34512 juil. 29 17:38 rxecho*

**Comment by f6bvp** [comment]
Hi David,I replied directly on GitHub.I am pretty sure recent install issues are due to environmental changes.There are a number of warnings when running autogen.sh ./configure on AX25tools and others.There are also some suggestions in order to cure warnings.Someone more familiar than me with AC_  declarations could probably update configure.ac accordingly.I performed uggly changes manually in config.h and could perform compilation and install AX25tools.But this is not the way it should be done.Dr Bernard Pidoux73 de Bernard, F6BVPhttp://radiotelescope-lavillette.frLe 28 juil. 2023 à 19:14, David Ranch ***@***.***> a écrit :﻿
Consider trying the following to see if these bring in some missing dependencies:
sudo apt install build-essential
sudo apt install zlib1g-dev
sudo apt install libncursesw5-dev

**Comment by ve7fet** [comment]
Specifically for the mode_t and pid_t errors when trying to compile the ax25tools, there is a change that needs to be made to configure.ac:

`AC_CHECK_HEADERS([arpa/inet.h fcntl.h limits.h netdb.h netinet/in.h paths.h \
                  pty.h sys/file.h sys/ioctl.h sys/param.h sys/socket.h sys/time.h sys/types.h \
                  syslog.h termios.h utime.h utmp.h zlib.h],,AC_MSG_ERROR([Required headers missing; aborting]))
`

Per the above, `sys\types.h` needs to be added to AC_CHECK_HEADERS.

That should allow mode_t and pid_t to properly define and not get broken in config.h (which David was trying to patch around).

I am going through all the autoconf files, and will be fixing some of the obsolete checks shortly. However, this should fix this particular error.

**Comment by ve7fet** [comment]
Should be resolved in this commit:

[ecbd544](https://github.com/ve7fet/linuxax25/commit/ecbd544bbc8f2ddce1265c6a8116ec4da4825128)
