### ISSUE TITLE
debuild -us -uc error

### ISSUE THREAD

**Issue by yv6eda** [ve7fet/linuxax25#17]
Hi! Sorry, I'm new. I try to build this and give me this error.
I'm trying to create a packet stadion with a KPC3 and an Armbian Inovato Quadra box.
Any help will be very appreciated!
Jorge VE3EAD 

dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package libax25
dpkg-buildpackage: info: source version 1.2.2
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Lee Woldanski <ve7fet@tparc.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture arm64
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-exec
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed

**Comment by ve7fet** [comment]
Hmm... did you try installing the missing package?

`Unmet build dependencies: dh-exec`

I'd try installing the dh-exec package with your package manager.

On the other hand, you don't have to build a package... you could just build and install the source with the normal commands such as:

`./configure && make && make install`


Lee

**Comment by yv6eda** [comment]
Hi Lee! Thanks for your response. I really have no clue what I'm doing. I
have no programming skills or knowledge of Linux. I'm following some
instructions from here (
http://www.trinityos.com/HAM/CentosDigitalModes/RPi/rpi4-setup.html#0.intro
) (Section  18.a Install libax25:)
Anyway, thanks again!
Jorge

**Comment by dranch** [comment]
Hello Jorge, 
Did you install all the required dependencies per https://www.trinityos.com/HAM/CentosDigitalModes/RPi/rpi-setup.html#17.install-compiler-toolchain ?  All of those packages are required to properly build and package the Linux AX.25 code.
