### ISSUE TITLE
After upAX25.sh simlink Libax25.so.0

### ISSUE THREAD

**Issue by pd2lt** [ve7fet/linuxax25#4]
When I used updAX25.sh. I encountered a problem. There was a problem finding libax25.so.0. I have to make a simlink. Also with libax25io.so.0

pd2lt@pi1lap:/usr/local/src/ax25# fbb -s -a
Checking fbb tree.... Ok
Checking fbb configuration :
/usr/local/sbin/xfbbd: error while loading shared libraries: libax25.so.0: cannot open shared object file: No such file or directory
Configuration error ! Giving up.
Please read file /usr/local/var/ax25/fbb/ERROR.SYS

Escape character is '^]'.
uronode: error while loading shared libraries: libax25io.so.0: cannot open shared object file: No such file or directory
Connection closed by foreign host.

Simlink
ln -s /usr/local/lib/libax25.so.1 /usr/lib/libax25.so.0
ln -s /usr/local/lib/libax25io.so.1 /usr/lib/libax25.io.so.0

No problem, but it's worth mentioning.
Maybe it's known, but I've never read it.
Thanks for the work, works perfectly.
Using Debian Wheezy 3.2.0-4-686-pae

73 Niels PD2LT

**Comment by f6bvp** [comment]
Hi Niels,

This is strange for xfbbd does not require libax25.so.0 !
I have never seen this error.
Did you us updfbb.sh script in order to install FBB ?
However we could arrange updAX25.sh script in order to add libax25.so.0  symlink that is required by some other AX25 applications.

73 de Bernard f6bvp

**Comment by pd2lt** [comment]
Hi Bernard,

No, I have not used updfbb.sh. There may be is the problem.
I have updated fbb two weeks ago to V7.0.8-beta3.

73 Niels pd2lt

**Comment by k4gbb** [comment]
The only time you need libax25.so.0 is if you are using a tnc-pi.

<<Charley>>

**Comment by f6bvp** [comment]
Charley,

Many thanks for providing us a precision about the library needed when 
using TNC-pi.

I did not remember that, although I have two nodes running FBB with 
modem device TNC-Pi.

This means that the specific symlink should be built an added in 
updAX25.sh script.

Bernard



Le 24/09/2017 à 23:56, Charley a écrit :
> The only time you need libax25.so.0 is if you are using a tnc-pi.
>
> <<Charley>>
>

**Comment by k4gbb** [comment]
I didn't add it to the Update script, but it is included in the
Instax25.new script.

**Comment by pd2lt** [comment]
I'm not using a tcn-pi. My bbs is running on a desktop. But ok, i will add it my self. If i use the script again. 

Thank you
73 Niels pd2lt

**Comment by pa2snk** [comment]
Using ax25-node i get the same error.. the symlink does not do the job for me.
think ax25-node is looking for the files at another place..

**Comment by f6bvp** [comment]
Hi

Debian keeps installing Ax25 libraries and builds Debian packages applications looking for ax25 libraries  in /usr/lib while most ham applications are looking for in /usr/local/lib .
Check if this is your case with :
ls -la /usr/lib/libax25*
In your case a dedicated symlink should solve the issue:
ln -s /usr/local/ lib/libax25.so.0 /usr/lib/libax25.so.0

73 de Bernard f6bvp

Envoyé de mon iPhone

**Comment by f6bvp** [comment]
Hi,
I just performed apt-get install ax25-node on my raspbian stretch raspberry Pi.
Then I started it and it complained  about not finding libax25io.so.0
Then I made the following symlink:
ln -s /usr/local/lib/libax25io.so.1.0.0  /usr/lib/libax25io.so.0

After that, no more complaints about ax25 missing library.

73 de Bernard f6bvp

**Comment by pa2snk** [comment]
Made the wo symlinks again for libax25io and libax25.
Problem is now solved 
Tnx for your help Bernard !
will post this on our facebook page in case anyone else runs in it.

73 Danny PA2SNK @ PI8SNK

**Comment by f6bvp** [comment]
Hi Danny,
Glad it is working.
However ax25-node seems to be obsolete. It does not work even after I compile it with debug option.
I would recommend the use of uronode from Ryan N1URO.

73 de Bernard f6bvp

**Comment by pa2snk** [comment]
I have no problems here running with ax25-node.
Uronode does not seem to have more things that i need for now.
Maybe in the future i will upgrade to uronode.

Danny PA2SNK

**Comment by pd2lt** [comment]
Hi Danny,

Maybe is de libax25 updated. I don`t know.
I create a simlink against
Simlink
ln -s /usr/local/lib/libax25.so.1 /usr/lib/libax25.so.0
ln -s /usr/local/lib/libax25io.so.1 /usr/lib/libax25.io.so.0

And you needs a simlink against.
ln -s /usr/local/lib/libax25.so.0 /usr/lib/libax25.so.0
ln -s /usr/local/lib/libax25io.so.1.0.0 /usr/lib/libax25io.so.0

I have libax25io.so.1
You have libax25.so.0

lrwxrwxrwx 1 root staff 18 Dec 2 2017 libax25io.so -> libax25io.so.1.0.0
lrwxrwxrwx 1 root staff 18 Dec 2 2017 libax25io.so.1 -> libax25io.so.1.0.0
-rwxr-xr-x 1 root staff 28462 Dec 2 2017 libax25io.so.1.0.0
-rwxr-xr-x 1 root staff 934 Dec 2 2017 libax25.la
lrwxrwxrwx 1 root staff 16 Dec 2 2017 libax25.so -> libax25.so.1.0.0
lrwxrwxrwx 1 root staff 16 Dec 2 2017 libax25.so.1 -> libax25.so.1.0.0

I think it went wrong with what you’ve read on the internet. There is a difference in the libraries.

Thanks for the reply…
Here we learn something from.

73 Niels PD9Q

Or it might be that I do not understand it.

-----Original Message-----

**Comment by dranch** [comment]
Just to add on to Bernard's comment about ax25-node being obsolete, it also has several known security issues.  Since it doesn't have any active maintainer, it's generally recommended to use N1URO's "uronode" program which is receiving enhancements and updates. 

Pd2lt, please close this Github ticket since this issue is related to a different package (ax25-node).
