### ISSUE TITLE
Porting to GCC 10: Defaults to -fno-common

### ISSUE THREAD

**Issue by hobbes1069** [ve7fet/linuxax25#7]
https://gcc.gnu.org/gcc-10/porting_to.html#common

https://bugzilla.redhat.com/show_bug.cgi?id=1799182
https://bugzilla.redhat.com/show_bug.cgi?id=1799183

**Comment by ve7fet** [comment]
This is NOT the official source for AX-25. See http://www.linux-ax25.org/wiki/Main_Page as stated on the main page.

There you will find the official maintainers of the source, and they will need to patch it accordingly.

This is just a fork.

**Comment by hobbes1069** [comment]
I have informed Ralf as well I just posted the issue here since Fedora is currently using this fork, however it would be great if the two could merge :)
